server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

spring:
  codec:
    max-in-memory-size: 50MB
  cloud:
    gateway:
      httpserver:
        request:
          max-initial-line-length: 16KB
          max-header-size: 16KB
          max-chunk-size: 50MB
      httpclient:
        wiretap: false
        max-initial-line-length: 16KB
        max-header-size: 16KB
        response-timeout: 30s
        # this is the one you're after
        max-in-memory-size: 52428800   # 50MB in bytes
      routes:
        - id: context-auth-login
          uri: ${CONTEXT_AUTH_HOST:http://localhost:8081}
          predicates:
            - Path=/login
            - Method=POST
          filters:
            - RewritePath=/login, /api/frontend/v1/auth/login
        - id: context-auth-users
          uri: ${CONTEXT_AUTH_HOST:http://localhost:8081}
          predicates:
            - Path=/users/**
            - Header=app-context-token
          filters:
            - RewritePath=/users(?<segment>/?.*), /api/frontend/v1/users${segment}
        - id: payments-upload
          uri: ${PAYMENTS_HOST:http://localhost:8082}
          predicates:
            - Path=/payments/upload/**
            - Header=app-context-token
          filters:
            - RewritePath=/payments/upload(?<segment>/?.*), /api/v1/files/rest/upload${segment}
        - id: payments-imports
          uri: ${PAYMENTS_HOST:http://localhost:8082}
          predicates:
            - Path=/payments/import/**
            - Header=app-context-token
          filters:
            - RewritePath=/payments/import(?<segment>/?.*), /api/v1/imports${segment}