server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: context-auth-login
          uri: ${CONTEXT_AUTH_HOST:http://localhost:8081}
          predicates:
            - Path=/login
            - Method=POST
          filters:
            - RewritePath=/login, /api/frontend/v1/auth/login
        - id: context-auth-users
          uri: ${CONTEXT_AUTH_HOST:http://localhost:8081}
          predicates:
            - Path=/users/**
            - Header=app-context-token
          filters:
            - RewritePath=/users(?<segment>/?.*), /api/frontend/v1/users$\{segment}
        - id: posts
          uri: ${POSTS_HOST:http://localhost:8082}
          predicates:
            - Path=/posts/**
            - Header=app-context-token
          filters:
            - RewritePath=/posts(?<segment>/?.*), /api/frontend/v1/posts\{segment}